name 'example_cookbook'
maintainer 'Stephen Rufle'
maintainer_email 'srufle@gmail.com'
license 'GPL3.0'
description 'Installs/Configures example_cookbook'
long_description 'Installs/Configures example_cookbook'
version '0.1.0'
